services:
  tor:
    container_name: tor_service
    # Run the Dockerfile on the root directory
    build: ./
    # Bind host ports to container ports
    ports:
      - "${PORT_HOST_NGINX:-8080}:${PORT_CONT_NGINX:-80}"
      - "${PORT_HOST_SSH:-4242}:${PORT_CONT_SSH:-4242}"
    # Always restart the container unless it is stopped manually
    restart: unless-stopped
    # Load environment variables from .env file
    env_file: 
      - .env
    # Declare environment variables to get warnings if they are
    # missing from the .env file
    environment:
      SSH_USER: ${SSH_USER}
      SSH_PWD: ${SSH_PWD}
      PORT_HOST_NGINX: ${PORT_HOST_NGINX}
      PORT_CONT_NGINX: ${PORT_CONT_NGINX}
      PORT_HOST_SSH: ${PORT_HOST_SSH}
      PORT_CONT_SSH: ${PORT_CONT_SSH}
    # A single value that sets a memory limit for the Docker container,
    # analogous to its `docker run` counterpart.
    #
    # Do `docker ps -s` to check the actual size of the container
    mem_limit: 512m  # MB
    # Mount paths as volumes, optionally specifying a path on the host machine
    # (HOST:CONTAINER), or an access mode (HOST:CONTAINER:ro):
    # Read-Only (ro) / Read-Write (rw)
    volumes:
      - ./html:/var/www/html:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sshd_config:/etc/ssh/sshd_config:ro
      - ./torrc:/etc/tor/torrc:ro
