services:
  nginx:
    image: nginx:alpine
    container_name: nginx_tor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
    depends_on:
      - tor

  tor:
      image: alpine:latest
      container_name: tor_service
      volumes:
        - ./torrc:/etc/tor/torrc
      command: ["sh", "-c", "apk add --no-cache tor && tor"]
      ports:
        - "9050:9050"

  ssh:
      image: linuxserver/openssh-server
      container_name: ssh_server
      environment:
        - PUID=1000
        - PGID=1000
        - PASSWORD_ACCESS=true
        - USER_NAME=user
        - USER_PASSWORD=yourpassword
      volumes:
        - ./sshd_config:/etc/ssh/sshd_config
      ports:
        - "4242:22"