services:
  tor:
    container_name: tor_service
    build: .
    ports:
      - "8080:80"
      - "4242:4242"
    restart: unless-stopped
    env_file: 
      - .env  # Load environment variables from .env file
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sshd_config:/etc/ssh/sshd_config
      - ./torrc:/etc/tor/torrc
    entrypoint: /usr/local/bin/setup.sh
